name = "auth_server"
version = "1.0.0"
repository = { type = "github", user = "Adophilus", repo = "auth-server" }
description = "Just a simple auth server written in gleam"
links = [
  { title = "GitHub", href = "https://github.com/Adophilus/auth-server" },
  { title = "Website", href = "https://adophilus.github.io/auth-server" },
]
# licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
wisp = "~> 0.12"
mist = "~> 0.17"
gleam_http = "~> 3.6"
gleam_json = "~> 1.0"
gleam_erlang = "~> 0.24"
gleam_httpc = "~> 2.1"
sqlight = "~> 0.9"
gleam_crypto = "~> 1.3"
gwt = "~> 0.1"
ids = ">= 0.12.0 and < 1.0.0"
rada = ">= 0.4.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
